//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SciFiGenerator2.0.rc

#define MAX_LOADSTRING			100
#define WSIZE					256
#define MODLIST_SIZE			1024
#define DATASET_SIZE			8192

/*---------------------------------------------
		Button Commands
---------------------------------------------*/

#define BUTTON_GENERATE				1
#define BUTTON_GENERAL				2
#define BUTTON_SYSTEM				3
#define BUTTON_PLANET				4
#define BUTTON_SURFACE				5
#define BUTTON_SPECIAL				6
#define BUTTON_ADVANCED				7

#define BUTTON_UPDATEPRESET			8
#define BUTTON_SAVEPRESET			9
#define BUTTON_SETOUTPUT			10

#define BUTTON_NAME_STAR			11
#define BUTTON_NAME_PLANET			12
#define BUTTON_NAME_MOON			13
#define BUTTON_NAME_DWARFMOON		14
#define BUTTON_NAME_SHIP_ALL		15
#define BUTTON_NAME_SHIP_COLONY		16
#define BUTTON_NAME_SHIP_INSTRUMENT	17
#define BUTTON_NAME_SHIP_SATELLITE	18
#define BUTTON_NAME_SHIP_STATION	19
#define BUTTON_NAME_DATASET			20
#define BUTTON_NAME_SIMPLE			21
#define BUTTON_NAME_UPDATE			22
#define BUTTON_NAME_LOAD_VECTORS	23
#define BUTTON_NAME_SAVEPRESET		24

#define BUTTON_TEST_NAMES			25

#define BUTTON_BROWSE_STAR_FOLDER	26
#define BUTTON_BROWSE_PLANET_FOLDER	27
#define BUTTON_BROWSE_MODELS_FOLDER	28

//#define BUTTON_ADV_

/*---------------------------------------------
		Info Box IDs
---------------------------------------------*/

#define IB_DEBUG				1000
#define IB_SEED					1001
#define IB_NUMBEROFRUNS			1002
#define IB_STAROUTPUTFOLDER		1016
#define IB_SELECTPRESET			1024
#define IB_SAVEPRESET			1025
#define IB_PLANETOUTPUTFOLDER	1026
#define IB_SELECTNAMEPRESET		1037
#define IB_SAVENAMEPRESET		1038

#define IB_SMARTPLACEMENT		1003
#define IB_MINPLANETNUMBER		1004
#define IB_DISTANCE				1005
#define IB_PLANETSPACING		1006
#define IB_ECCENTRICITY			1007
#define IB_INCLINATION			1008
#define IB_OBLIQUITY			1009
#define IB_STARCLASS			1010
#define IB_GENERATEDWARFPLANET	1027
#define IB_DWARFPALNETCHANCE	1028
#define IB_WEIGHTEDMOONS		1039
#define IB_MOONDISTANCEBOUNDARY 1040

#define IB_LIFEORGANICCHANCE	1011
#define IB_LIFEEXOTICCHANCE		1012
#define IB_LIFEMULTICHANCE		1013
#define IB_FORCELIFE			1014
#define IB_TRADITIONALLIFE		1015

#define IB_SHIPCHANCE			1017
#define IB_SHIPSNEEDLIFE		1018
#define IB_MODELSFOLDER			1019

#define IB_EXOTICORBIT			1020
#define IB_EXOTICOBLIQUITY		1021
#define IB_EXOTICCOMPANION		1022
#define IB_EXOTICDEBRISRING		1023

#define IB_NAMEPREMODS			1029
#define IB_NAMEPOSTMODS			1030
#define IB_NAMENUMBERMODS		1031
#define IB_NAMEPREMODLIST		1032
#define IB_NAMEPOSTMODLIST		1033
#define IB_NAMEMOONS			1034
#define IB_MARKOV				1035
#define IB_SIMPLEGENERATOR		1036
#define IB_WORDPERCENT			1041

#define IB_GENERATECOMPOSITION	1042

/*---------------------------------------------
		Check Box IDs
---------------------------------------------*/

#define CB_DEBUG				1500

#define CB_SMARTPLACEMENT		1501
#define CB_GENERATEDWARFPLANET	1502
#define CB_WEIGHTEDMOONS		1503

#define CB_TRADITIONALLIFE		1504
#define CB_FORCELIFE			1505

#define CB_SHIPSNEEDLIFE		1506
#define CB_GENERATECOMPOSITION	1507

/*---------------------------------------------
		Trackbar IDs
---------------------------------------------*/

/*---------------------------------------------
		Name Variable Check Box IDs
---------------------------------------------*/

#define NVCB_SIMPLEGENERATOR		1630

#define NVCB_STARPREMOD				1600
#define NVCB_STARPOSTMOD			1601
#define NVCB_STARNUMBERMOD			1602

#define NVCB_PLANETPREMOD			1603
#define NVCB_PLANETPOSTMOD			1604
#define NVCB_PLANETNUMBERMOD		1605

#define NVCB_MOONPREMOD				1606
#define NVCB_MOONPOSTMOD			1607
#define NVCB_MOONNUMBERMOD			1608

#define NVCB_DWARFMOONPREMOD		1609
#define NVCB_DWARFMOONPOSTMOD		1610
#define NVCB_DWARFMOONNUMBERMOD		1611

#define NVCB_NAMETERRAMOONS			1612
#define NVCB_NAMEGASMOONS			1613
#define NVCB_NAMETERRADWARFMOONS	1614
#define NVCB_NAMEGASDWARFMOONS		1615

#define NVCB_SHIPALLPREMOD				1616
#define NVCB_SHIPALLPOSTMOD				1617

#define NVCB_SHIPCOLONYPREMOD			1618
#define NVCB_SHIPCOLONYPOSTMOD			1619
#define NVCB_SHIPCOLONYNUMBERMOD		1620

#define NVCB_SHIPINSTRUMENTPREMOD		1621
#define NVCB_SHIPINSTRUMENTPOSTMOD		1622
#define NVCB_SHIPINSTRUMENTNUMBERMOD	1623

#define NVCB_SHIPSATELLITEPREMOD		1624
#define NVCB_SHIPSATELLITEPOSTMOD		1625
#define NVCB_SHIPSATELLITENUMBERMOD		1626

#define NVCB_SHIPSTATIONPREMOD			1627
#define NVCB_SHIPSTATIONPOSTMOD			1628
#define NVCB_SHIPSTATIONNUMBERMOD		1629







#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_SOLARSYSTEMGENERATOR20_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_SOLARSYSTEMGENERATOR20			107
#define IDI_SMALL				108
#define IDC_SOLARSYSTEMGENERATOR20			109
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
